# Generated by Django 3.1.4 on 2020-12-11 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team', models.CharField(max_length=50, verbose_name='Home team')),
                ('away_team', models.CharField(max_length=50, verbose_name='Away team')),
                ('home_goals', models.IntegerField(verbose_name='Home goals')),
                ('away_goals', models.IntegerField(verbose_name='Away goals')),
                ('season', models.CharField(max_length=10, verbose_name='Season')),
                ('date', models.DateField(verbose_name='Date')),
                ('league', models.CharField(max_length=30, verbose_name='League')),
                ('country', models.CharField(max_length=30, verbose_name='Country')),
            ],
        ),
    ]
