# Generated by Django 3.1.4 on 2020-12-13 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0002_auto_20201213_0114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaguestandings',
            name='standings',
        ),
        migrations.AddField(
            model_name='leaguestandings',
            name='position',
            field=models.IntegerField(default=0, verbose_name='Position'),
        ),
    ]
