# Generated by Django 3.1.4 on 2020-12-13 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0003_auto_20201213_1247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaguestandings',
            old_name='played',
            new_name='games_played',
        ),
    ]
