# Generated by Django 3.1.4 on 2020-12-17 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0006_auto_20201213_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaguestandings',
            name='longest_draw_streak',
            field=models.IntegerField(default=-1, verbose_name='Longest draw streak'),
        ),
        migrations.AddField(
            model_name='leaguestandings',
            name='longest_loss_streak',
            field=models.IntegerField(default=-1, verbose_name='Longest loss streak'),
        ),
        migrations.AddField(
            model_name='leaguestandings',
            name='longest_unbeaten_streak',
            field=models.IntegerField(default=-1, verbose_name='Longest unbeaten streak'),
        ),
        migrations.AddField(
            model_name='leaguestandings',
            name='longest_win_streak',
            field=models.IntegerField(default=-1, verbose_name='Longest win streak'),
        ),
    ]
