# Generated by Django 3.1.4 on 2020-12-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0007_auto_20201217_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrossLeagueStandings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0, verbose_name='Position')),
                ('team', models.CharField(max_length=50, verbose_name='Team')),
                ('games_played', models.IntegerField(verbose_name='Games played')),
                ('avg_points', models.FloatField(verbose_name='Average points')),
                ('avg_goal_difference', models.FloatField(verbose_name='Average goal difference')),
                ('win_percent', models.FloatField(verbose_name='Win percent')),
                ('loss_percent', models.FloatField(verbose_name='Loss percent')),
                ('draw_percent', models.FloatField(verbose_name='Draw percent')),
                ('avg_goals_scored', models.FloatField(verbose_name='Average goals scored')),
                ('avg_goals_allowed', models.FloatField(verbose_name='Average goals allowed')),
                ('clean_sheets_percent', models.FloatField(verbose_name='Clean sheets percent')),
                ('clean_sheets_against_percent', models.FloatField(verbose_name='Clean sheets against percent')),
                ('big_win_percent', models.FloatField(verbose_name='Big win percent')),
                ('big_loss_percent', models.FloatField(verbose_name='Big loss percent')),
                ('results_string', models.CharField(default='', max_length=38, verbose_name='Results string')),
                ('cumulative_points', models.CharField(default='', max_length=200, verbose_name='Cumulative points')),
                ('cumulative_goal_difference', models.CharField(default='', max_length=200, verbose_name='Cumulative goal difference')),
                ('longest_win_streak', models.IntegerField(default=-1, verbose_name='Longest win streak')),
                ('longest_loss_streak', models.IntegerField(default=-1, verbose_name='Longest loss streak')),
                ('longest_draw_streak', models.IntegerField(default=-1, verbose_name='Longest draw streak')),
                ('longest_unbeaten_streak', models.IntegerField(default=-1, verbose_name='Longest unbeaten streak')),
                ('league', models.CharField(max_length=30, verbose_name='League')),
            ],
            options={
                'verbose_name': 'Cross League Standings',
                'verbose_name_plural': 'Cross League Standings',
            },
        ),
    ]
